config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
  resource :timeline, only: [:show]

  resources :articles do
    resources :comments, only: [:index, :create]

    resource :like, only: [:show, :create, :destroy]
  end

  resources :accounts, only: [:show] do
    resources :followings, only: [:index]
    resources :followers, only: [:index]
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end

  resource :profile, only: [:show, :edit, :update]
end

app/views/commons/_articles.html.haml
.container
  - @article.each do |article|
    .article
      .article_nav
        = link_to account_path(article.user) do
          = image_tag article.user.avatar_image, class:'article_nav_avatar'
        .article_nav_text
          .article_nav_text_name
            %p= article.user.username
          .article_nav_text_time
            %p= article.display_created_at
      .article_content
        - article.eyecatch.each do |eyecatch| 
          = image_tag eyecatch, class: 'article_content_image'
      - if user_signed_in?
        .article_action
          .article_heart.hidden.active-heart{:id => article.id}
            = image_tag 'heart-active.svg', class: 'article_icon'
          .article_heart.hidden.inactive-heart{:id => article.id}
            = image_tag 'heart.svg', class: 'article_icon'
          .article_comment
            = link_to article_comments_path(article) do
              = image_tag 'comment.png', class: 'article_icon'
          .article_share
            = link_to "https://twitter.com/share?url=#{request.url}", title: 'Twitter', target: '_blank' do
              = image_tag 'share.png', class: 'article_icon'
       
      .article_liked
        %p 「いいね!」
        %span= article.like_count
        %p 件
      .article_comments
        %p 「コメント」
        %span= article.comment_count
        %p 件
      .article_text
        .article_user_name
          %p ____sktm____
        .article_text_content
          %p= article.content

= javascript_pack_tag 'article'

app/views/commons/_profile.html.haml
.container
  .profilePage_header
    .profile_back_icon
      = link_to image_tag('back.svg'), :back
    .profilePage_user_actionButton
      - if user == current_user
        =link_to 'Edit Profile', edit_profile_path
      - else
        - if current_user&.has_followed?(user)
          =link_to 'Unfollow', account_unfollows_path(user), data: {method: 'post'}
        - else
          =link_to 'Follow', account_follows_path(user), data: {method: 'post'}
    .profile_username
      = user.username
    

  .avatar
    = image_tag user.avatar_image, class:'profile_usericon'

  .account_status
    .post_status
      %p.status-count= user.article_count
      %p.status-text Posts
    = link_to account_followers_path(user) do
      .followers_status
        %p.status-count= user.follower_count
        %p.status-text Followers
    = link_to account_followings_path(user) do
      .following_status
        %p.status-count= user.following_count
        %p.status-text Following

= javascript_pack_tag 'article'